### ISSUE TITLE
orders (full): wrong sort order leads to overlapping data entries in batches

### ISSUE THREAD

**Issue by heldchen** [boxalino/data-integration-magento2#3]
the query used to batch the orders is using a wrong sort order: `SELECT `s_o`.* FROM `sales_order` AS `s_o` WHERE (s_o.store_id IN ('5', '8') OR s_o.store_id = 0) ORDER BY `s_o`.`entity_id` DESC LIMIT 50 OFFSET 50` 

in live systems where new orders come in while long running full exports, this will result in some of the orders appearing multiple times in the batches. using ASC has the added benefit that it's using the natural sort order of the rows in the tables, further speeding up the data reads slightly.

**patch**
```
diff --git a/Model/ResourceModel/Document/Order/EntityResourceTrait.php b/Model/ResourceModel/Document/Order/EntityResourceTrait.php
--- a/Model/ResourceModel/Document/Order/EntityResourceTrait.php	(revision 185dce7e69de7c7bb95e63b9b37125d6e2ccf095)
+++ b/Model/ResourceModel/Document/Order/EntityResourceTrait.php	(date 1641663891709)
@@ -51,7 +51,7 @@
             $select = $this->addInstantCondition($select);
         }
 
-        $select->order("s_o.entity_id DESC")
+        $select->order("s_o.entity_id ASC") // must use ASC as in production systems there will be new orders while exporting
             ->limitPage((int)$this->getChunk(), (int)$this->getBatch());
 
         return $select;

```

**Comment by dannegwork** [comment]
https://github.com/boxalino/data-integration-magento2/commit/4fb2591e733d9a22c4b991a9a75f37b457222a61

tag 1.2.3 will have the recommended fix for live environments.
thank you!
