### ISSUE TITLE
orders (full): memory leak and/or unreleased resources

### ISSUE THREAD

**Issue by heldchen** [boxalino/data-integration-magento2#4]
when using batching, the memory consumption is constantly growing during the exports. this can be observed regardless of the configured `batchsize` setting:
- batchsize `1000`: after exporting 1.3mio orders, the memory consumption was already at 8G
- batchsize `1000000`: after exporting 2.8mio orders, the memory consumption grew to 29G
- batchsize `1500000`: after exporting 2.4mio orders the memory consumption exceeded the available memory and the process was killed off

**Comment by dannegwork** [comment]
This was a noticed behavior from other environments as well. 
In the initial version (pre-stage release), there was no batch for the order/user export and the process was staggering on the client setup. The batch was added later on as a test-case to review if it would help the process (which also did not have the desired effect)

**Comment by heldchen** [comment]
the batching is a first step, without it the memory usage is exploding per run. currently, 300k orders-batchsize requires about 6gb data in-memory during loading/processing (before sending to bq) - which is totally fine. the issue here is that not all of this memory seems to be released after bq received the json data and the next batch processing starts. each following batch run adds some memory.

**Comment by dannegwork** [comment]
Yes, this indeed was the case.  When reaching high OFFSET values it becomes unsustainable using the batch.
On live environments (with a huge collection of orders/data) this problem occurs naturally.
We will adjust the flow to use the suggested SEEK strategy.

**Comment by heldchen** [comment]
hmm I'm not seeing the relation of memory to offset-vs-seek as the later only affects the query runtime, not the data in the php process? the recordset per batch in both strategies will be the same.

**Comment by dannegwork** [comment]
https://github.com/boxalino/data-integration-magento2/commit/7d346e58bff6dda7e0afebc2313707a0a8a74d29

the fix is available as of tag 1.2.6
